[[community]]
identifier = "about"
name = "Community"
weight = 10
# url = "/about/"

[[docs]]
identifier = "vale-cli"
name = "Vale CLI"
url = "/docs/vale-cli/"
weight = 10

[[docs]]
identifier = "topics"
name = "Topics"
url = "/docs/topics/"
weight = 20

[[docs]]
identifier = "vale-server"
name = "Vale Server"
url = "/docs/vale-server/"
weight = 30

[[docs]]
identifier = "integrations"
name = "Integrations"
url = "/docs/integrations/"
weight = 40

[[docs]]
external = true
identifier = "atom"
name = "Atom"
parent = "integrations"
url = "https://github.com/errata-ai/vale-atom"
weight = 10

[[docs]]
identifier = "emacs"
name = "Emacs"
parent = "integrations"
url = "https://github.com/abingham/flycheck-vale"
weight = 10

[[docs]]
identifier = "gh-actions"
name = "GitHub Actions"
parent = "integrations"
url = "https://github.com/errata-ai/vale-action"
weight = 10

[[docs]]
identifier = "jetbrains"
name = "Jetbrains"
parent = "integrations"
url = "https://plugins.jetbrains.com/plugin/16136-grazie-professional"
weight = 10

[[docs]]
identifier = "laravel"
name = "Laravel"
parent = "integrations"
url = "https://github.com/beyondcode/laravel-prose-linter"
weight = 10

[[docs]]
identifier = "obsidian"
name = "Obsidian"
parent = "integrations"
url = "https://github.com/marcusolsson/obsidian-vale"
weight = 10

[[docs]]
identifier = "oxygen"
name = "Oxygen XML"
parent = "integrations"
url = "https://www.oxygenxml.com/doc/versions/23.1/ug-editor/topics/vale-linter-addon.html"
weight = 10

[[docs]]
identifier = "sublime"
name = "Sublime Text"
parent = "integrations"
url = "https://github.com/errata-ai/SubVale"
weight = 10

[[docs]]
identifier = "vim"
name = "Vim"
parent = "integrations"
url = "https://github.com/dense-analysis/ale"
weight = 10

[[docs]]
identifier = "vscode"
name = "VS Code"
parent = "integrations"
url = "https://github.com/errata-ai/vale-vscode"
weight = 10

[[main]]
name = "Docs"
url = "/docs/vale-cli/installation/"
# url = "/docs/1.0/prologue/introduction/"
weight = 10

[[main]]
name = "Blog"
url = "https://medium.com/valelint"
weight = 20

[[main]]
name = "Community"
url = "/community/connect/"
weight = 20

[[main]]
identifier = "resources"
name = "Resources"
url = "/resources/"
weight = 30

[[main]]
identifier = "explorer"
name = "Rule Explorer"
parent = "resources"
url = "/explorer/"
weight = 40

[[main]]
identifier = "package-hub"
name = "Package Hub"
parent = "resources"
url = "/hub/"
weight = 50

[[main]]
identifier = "config-generator"
name = "Config Generator"
parent = "resources"
url = "/generator/"
weight = 60

[[main]]
identifier = "manual"
name = "CLI Manual"
parent = "resources"
url = "/manual/"
weight = 70

[[social]]
name = "GitHub"
post = "v0.1.0"
pre = '<i class="fab fa-github"></i>'
url = "https://github.com/errata-ai"
weight = 10

[[social]]
name = "Slack"
pre = '<i class="fab fa-slack"></i>'
url = "https://writethedocs.slack.com/archives/CBWQQ5E57"
weight = 20

# [[social]]
# name = "Youtube"
# pre = '<i class="fab fa-youtube"></i>'
# url = "https://www.youtube.com/channel/UCw-GUZljsD4zddL-nppAu9w"
# weight = 30

[[social]]
name = "Discord"
pre = '<i class="fab fa-discord"></i>'
url = "https://discord.gg/8S6HRxGgGq"
weight = 40

# [[footer]]
# name = "Privacy"
# url = "/privacy-policy/"
# weight = 10

[[hub]]
identifier = "browse"
name = "Browse"
url = "/hub/"
weight = 10

[[tertiary]]
name = "Submit a package"
pre = '<i class="fas fa-chevron-right"></i>'
url = "https://github.com/errata-ai/vale.sh"
weight = 10
