# Meta Data for SEO

## Homepage
description = "Vale is a command-line tool that brings code-like linting to prose. It's fast, cross-platform (Windows, macOS, and Linux), and highly customizable."
title = "Vale.sh"
titleAddition = "A linter for prose"
titleSeparator = "-"

## Documentation
# docsVersion = "0.3"

## Open Graph
# domainTLD = "doks.netlify.app"
# images = ["doks.png"]
# ogLocale = "en_US"
# titleHome = "Doks Theme"

## Twitter Cards
# twitterCreator = "@henkverlinde"
# twitterSite = "@getdoks"

## JSON-LD
# schemaType = "Person"
# schemaAuthor = "Henk Verlinde"
# schemaAuthorGitHub = "https://github.com/h-enk"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorTwitter = "https://twitter.com/henkverlinde"
# schemaGitHub = "https://github.com/h-enk/doks"
# schemaImage = "doks.png"
# schemaImageHeight = 640
# schemaImageWidth = 1280
# schemaLinkedIn = ""
# schemaLocale = "en-US"
# schemaLogo = "logo-doks.png"
# schemaLogoHeight = 512
# schemaLogoWidth = 512
# schemaName = "Doks"
# schemaSection = "blog"
# schemaTwitter = "https://twitter.com/getdoks"
# schemaType = "Organization"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
lqipWidth = "20x"
portraitPhotoWidths = [800, 700, 600, 500]
quality = 85
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://www.algolia.com/\">Algolia</a>, and <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>"

# Feed
copyRight = "Copyright (c) 2022 Joseph Kato"

# Alert
alert = false
alertDismissable = false
alertText = "Help Vale grow by supporting us on Open Collective. <a class=\"alert-link stretched-link\" href=\"https://opencollective.com/vale\" target=\"_blank\" rel=\"noopener\">Become a backer!</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/errata-ai/vale.sh"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
bootStrapJs = true
breadCrumb = false
clipBoard = true
darkMode = true
docsVersioning = false
flexSearch = false
fullWidth = true
highLight = false
instantPage = true
kaTex = false
lazySizes = true
multilingualMode = false

[menu]
[menu.section]
auto = false
collapsibleSidebar = true
